function(uvg_find_ccache)
  if(DEFINED UVG_CCACHE_EXECUTABLE)
    return()
  endif()
  message(STATUS "Looking for ccache")
  find_program(UVG_CCACHE_EXECUTABLE ccache)
  if(UVG_CCACHE_EXECUTABLE)
    message(STATUS "Looking for ccache - ${UVG_CCACHE_EXECUTABLE}")
  else()
    message(STATUS "Looking for ccache - not found")
  endif()
endfunction()

function(uvg_maybe_use_ccache)
  if(NOT UVG_ENABLE_CCACHE)
    return()
  endif()

  uvg_find_ccache()
  if(NOT UVG_CCACHE_EXECUTABLE)
    return()
  endif()

  set(CMAKE_C_COMPILER_LAUNCHER "${UVG_CCACHE_EXECUTABLE}" PARENT_SCOPE)
  set(CMAKE_CXX_COMPILER_LAUNCHER "${UVG_CCACHE_EXECUTABLE}" PARENT_SCOPE)
endfunction()
