name: uvg266_pr_tests

on:
  pull_request_target:
    types: [labeled]

jobs:

  basic-test:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: build
      run: cmake --build build --parallel
    - name: install
      run: cmake --install build --prefix "${PWD}"
    - name: test
      run: export PATH="/home/docker/bin:${PATH}" && ctest --test-dir build --parallel --timeout 1800 --output-on-failure

  test-ubsan:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    env:
      CC: gcc
      CFLAGS: -fsanitize=undefined -fno-sanitize-recover=all -fno-sanitize=alignment

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: build
      run: cmake --build build --parallel
    - name: install
      run: cmake --install build --prefix "${PWD}"
    - name: test
      run: export PATH="/home/docker/bin:${PATH}" && ctest --test-dir build --parallel --timeout 1800 --output-on-failure

  test-asan:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    env:
      CC: gcc
      CFLAGS: -fsanitize=address
      ASAN_OPTIONS: detect_leaks=0
      # AddressSanitizer adds some extra symbols so we expect a failure from
      # the external symbols test.
      XFAIL_TESTS: test_external_symbols

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: build
      run: cmake --build build --parallel
    - name: install
      run: cmake --install build --prefix "${PWD}"
    - name: test
      run: export PATH="/home/docker/bin:${PATH}" && ctest --test-dir build --parallel --timeout 1800 --output-on-failure

  # test-tsan:
    # runs-on: self-hosted
    # if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    # env:
      # CC: gcc
      # CFLAGS: -fsanitize=thread

    # steps:
    # - uses: actions/checkout@v2
      # with:
        # ref: ${{github.event.pull_request.head.ref}}
        # repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: build
      run: cmake --build build --parallel
    - name: install
      run: cmake --install build --prefix "${PWD}"
    - name: test
      run: export PATH="/home/docker/bin:${PATH}" && ctest --test-dir build --parallel --timeout 1800 --output-on-failure

  test-valgrind:
    runs-on: self-hosted
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')

    env:
      UVG266_OVERRIDE_angular_pred: generic

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: configure
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - name: build
      run: cmake --build build --parallel
    - name: install
      run: cmake --install build --prefix "${PWD}"
    - name: test
      run: export PATH="/home/docker/bin:${PATH}" && ctest --test-dir build --parallel --timeout 7200 --output-on-failure
